{% set name = "langchain-nomic" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_nomic-{{ version }}.tar.gz
  sha256: 3be4081a774a7adec006fdc59d6f2ccae751ade6e57427e15c0a5d5d227c116a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.1.46,<0.3
    - nomic >=3.0.29,<4.0.0
    - pillow >=10.3.0,<11.0.0

test:
  imports:
    - langchain_nomic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Nomic and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
