{% set name = "langchain-nomic" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_nomic-{{ version }}.tar.gz
  sha256: f7ced9b13fd8ef6d6b636424dc380e84652c33f23ce30071569f701cea39ccae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=1.0.0,<2.0.0
    - nomic >=3.5.3,<4.0.0
    - pillow >=10.3.0,<12.0.0

test:
  imports:
    - langchain_nomic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Nomic and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
